<?php
namespace App\Services;

use RuntimeException;

class ConversionWorkspaceService
{
    private array $allowedFormats = [
        'jpg', 'jpeg', 'png', 'webp', 'svg', 'gif',
        'pdf', 'docx', 'txt', 'html',
        'mp4', 'mov', 'avi', 'mkv',
        'mp3', 'wav', 'aac',
    ];

    public function validateUploads(array $files): array
    {
        $normalized = [];
        $names = $files['name'] ?? [];
        $tmpNames = $files['tmp_name'] ?? [];
        $sizes = $files['size'] ?? [];
        $errors = $files['error'] ?? [];

        foreach ($names as $index => $name) {
            if (($errors[$index] ?? UPLOAD_ERR_NO_FILE) !== UPLOAD_ERR_OK) {
                continue;
            }

            $extension = strtolower(pathinfo($name, PATHINFO_EXTENSION));
            if (!in_array($extension, $this->allowedFormats, true)) {
                throw new RuntimeException("Unsupported file format: {$extension}");
            }

            if (($sizes[$index] ?? 0) > 100 * 1024 * 1024) {
                throw new RuntimeException('One of the files exceeds the 100MB upload limit.');
            }

            $normalized[] = [
                'name' => preg_replace('/[^A-Za-z0-9._-]/', '-', basename((string) $name)),
                'tmp_name' => $tmpNames[$index] ?? '',
                'size' => (int) ($sizes[$index] ?? 0),
                'extension' => $extension,
            ];
        }

        return $normalized;
    }

    public function recommendFormat(string $sourceType, string $targetFormat): string
    {
        return match ($sourceType) {
            'image' => 'Recommended: WEBP for smaller web delivery and strong quality retention.',
            'document' => 'Recommended: PDF for universal compatibility and shareable output.',
            'video' => 'Recommended: MP4 (H.264-ready) for broad playback support and streaming.',
            'audio' => 'Recommended: MP3 for compatibility, WAV for mastering/export quality.',
            default => 'Smart suggestion: use WEBP for images, PDF for docs, MP4 for video, and MP3 for audio.',
        } . " Selected target: " . strtoupper($targetFormat) . '.';
    }

    public function convertBatch(array $uploads, string $targetFormat, string $sourceType = 'auto'): array
    {
        $results = [];
        $exportDir = dirname(__DIR__) . '/storage/exports';
        if (!is_dir($exportDir)) {
            mkdir($exportDir, 0775, true);
        }

        foreach ($uploads as $upload) {
            $baseName = pathinfo($upload['name'], PATHINFO_FILENAME);
            $outputFile = sprintf('%s/%s-%s.%s', $exportDir, $baseName, uniqid('converted-', true), $targetFormat);
            $summary = [
                'original_name' => $upload['name'],
                'source_type' => $sourceType,
                'target_format' => $targetFormat,
                'note' => 'Demo conversion output generated by FluxStudio Suite. Replace with FFmpeg/ImageMagick/LibreOffice workers in production.',
                'generated_at' => date(DATE_ATOM),
            ];

            file_put_contents($outputFile, json_encode($summary, JSON_PRETTY_PRINT));
            $shareToken = $this->createShareToken(basename($outputFile), 60);

            $results[] = [
                'name' => $upload['name'],
                'size' => $upload['size'],
                'target_format' => strtoupper($targetFormat),
                'download_url' => 'download.php?file=' . rawurlencode(basename($outputFile)),
                'share_url' => 'share.php?token=' . rawurlencode($shareToken),
                'expires_in' => '60 minutes',
                'watermark' => 'Free plan branding enabled on demo conversions.',
                'preview' => sprintf('Preview ready for %s → %s', $upload['name'], strtoupper($targetFormat)),
                'qr_text' => 'share.php?token=' . rawurlencode($shareToken),
            ];
        }

        return $results;
    }

    public function createShareToken(string $fileName, int $minutes = 60): string
    {
        $token = bin2hex(random_bytes(16));
        $shareDir = dirname(__DIR__) . '/storage/shares';
        if (!is_dir($shareDir)) {
            mkdir($shareDir, 0775, true);
        }

        file_put_contents($shareDir . '/' . $token . '.json', json_encode([
            'file' => $fileName,
            'expires_at' => time() + ($minutes * 60),
            'created_at' => time(),
        ], JSON_PRETTY_PRINT));

        return $token;
    }

    public function getShare(string $token): ?array
    {
        $path = dirname(__DIR__) . '/storage/shares/' . $token . '.json';
        if (!is_file($path)) {
            return null;
        }

        $payload = json_decode((string) file_get_contents($path), true);
        if (($payload['expires_at'] ?? 0) < time()) {
            return null;
        }

        return $payload;
    }
}
