<?php
require_once __DIR__ . '/functions.php';
require_once __DIR__ . '/partials.php';
require_admin();
$subjects = fetch_subjects($pdo);
$classes = fetch_classes($pdo);
$materials = $pdo->query('SELECT m.*, s.name subject_name, c.name class_name FROM materials m JOIN subjects s ON s.id=m.subject_id JOIN classes c ON c.id=m.class_id ORDER BY m.created_at DESC LIMIT 80')->fetchAll();
render_head('Admin Upload Panel');
?>
<div class="app-shell">
    <?php render_sidebar('materials'); ?>
    <main>
        <div class="topbar d-flex align-items-center justify-content-between"><button class="btn btn-ghost d-lg-none" data-sidebar-toggle><i class="bi bi-list"></i></button><div><div class="fw-bold">Admin Upload Panel</div><small class="text-muted-premium">Bulk upload, publish, and manage materials.</small></div><a class="btn btn-ghost" href="logout.php"><i class="bi bi-box-arrow-right"></i> Logout</a></div>
        <div class="content">
            <section class="hero-card glass reveal mb-4"><div class="row align-items-center g-4"><div class="col-lg-8"><span class="badge-soft mb-3 d-inline-flex"><i class="bi bi-cloud-arrow-up me-2 text-info"></i> Creator command center</span><h1 class="gradient-title mb-3">Upload beautiful resources at scale.</h1><p class="lead text-muted-premium">Auto-detect file types, route uploads to organized folders, prevent duplicates, and track usage from one premium SaaS-grade dashboard.</p></div><div class="col-lg-4"><div class="glass rounded-5 p-4"><div class="d-flex justify-content-between"><span>Files</span><strong><?= count($materials) ?></strong></div><div class="d-flex justify-content-between"><span>Subjects</span><strong><?= count($subjects) ?></strong></div><div class="d-flex justify-content-between"><span>Classes</span><strong><?= count($classes) ?></strong></div></div></div></div></section>

            <section class="upload-card glass p-4 p-lg-5 reveal mb-4">
                <h2 class="fw-bold mb-4"><i class="bi bi-magic text-info"></i> Smart upload</h2>
                <form id="uploadForm" action="upload_handler.php" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
                    <div class="row g-3">
                        <div class="col-lg-6"><label class="form-label">Title</label><input name="title" class="form-control" required placeholder="e.g. Calculus Chapter 4 Notes"></div>
                        <div class="col-lg-3"><label class="form-label">Subject</label><select name="subject_id" class="form-select" required><?php foreach ($subjects as $subject): ?><option value="<?= (int)$subject['id'] ?>"><?= e($subject['name']) ?></option><?php endforeach; ?></select></div>
                        <div class="col-lg-3"><label class="form-label">Class</label><select name="class_id" class="form-select" required><?php foreach ($classes as $class): ?><option value="<?= (int)$class['id'] ?>"><?= e($class['name']) ?></option><?php endforeach; ?></select></div>
                        <div class="col-12"><label class="form-label">Description</label><textarea name="description" class="form-control" rows="3" placeholder="Short description for previews and search."></textarea></div>
                        <div class="col-lg-8"><label class="form-label">Tags</label><input name="tags" class="form-control" placeholder="algebra, exam prep, worksheet"></div>
                        <div class="col-lg-4"><label class="form-label">Thumbnail</label><input type="file" name="thumbnail" accept="image/*" class="form-control"></div>
                        <div class="col-12"><label class="upload-zone w-100" id="dropZone"><i class="bi bi-cloud-arrow-up display-4 text-info"></i><strong class="d-block mt-2">Drop files here or click to browse</strong><small class="text-muted-premium">PDF, docs, images, videos, ZIP up to 100 MB each. Multi-file upload supported.</small><input id="fileInput" type="file" name="materials[]" multiple hidden></label><div id="filePreviewList" class="mt-3"></div></div>
                        <div class="col-12 d-flex gap-4 flex-wrap"><div class="form-check form-switch"><input class="form-check-input" name="is_published" type="checkbox" checked><label class="form-check-label">Publish</label></div><div class="form-check form-switch"><input class="form-check-input" name="is_featured" type="checkbox"><label class="form-check-label">Featured</label></div><div class="form-check form-switch"><input class="form-check-input" name="is_premium" type="checkbox"><label class="form-check-label">Premium</label></div></div>
                        <div class="col-12"><div id="uploadProgress" class="progress d-none mb-3"><div class="progress-bar progress-bar-striped progress-bar-animated" style="width:0%"></div></div><button class="btn btn-premium btn-lg px-5"><i class="bi bi-rocket-takeoff"></i> Upload materials</button></div>
                    </div>
                </form>
            </section>

            <div class="row g-4 mb-4">
                <div class="col-lg-6"><form class="glass rounded-5 p-4" method="post" action="admin_actions.php"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add_subject"><h4>Add subject</h4><div class="row g-2"><div class="col"><input name="name" class="form-control" required placeholder="Subject name"></div><div class="col-auto"><input name="color" type="color" class="form-control form-control-color" value="#4f46e5"></div><div class="col-auto"><button class="btn btn-premium">Add</button></div></div></form></div>
                <div class="col-lg-6"><form class="glass rounded-5 p-4" method="post" action="admin_actions.php"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="add_class"><h4>Add class</h4><div class="row g-2"><div class="col"><input name="name" class="form-control" required placeholder="Class name"></div><div class="col-auto"><button class="btn btn-premium">Add</button></div></div></form></div>
            </div>

            <section class="glass rounded-5 p-4 reveal"><h2 class="fw-bold mb-4"><i class="bi bi-kanban text-info"></i> Manage materials</h2><div class="table-responsive"><table class="table table-dark-premium align-middle"><thead><tr><th>Material</th><th>Subject</th><th>Class</th><th>Stats</th><th>Status</th><th></th></tr></thead><tbody><?php foreach ($materials as $material): ?><tr><td><div class="fw-bold"><?= e($material['title']) ?></div><small class="text-muted-premium"><?= e($material['original_file_name']) ?> · <?= e(format_bytes((int)$material['file_size'])) ?></small></td><td><?= e($material['subject_name']) ?></td><td><?= e($material['class_name']) ?></td><td><i class="bi bi-eye"></i> <?= (int)$material['views_count'] ?> · <i class="bi bi-download"></i> <?= (int)$material['downloads_count'] ?></td><td><?= $material['is_published'] ? '<span class="badge bg-success">Published</span>' : '<span class="badge bg-secondary">Draft</span>' ?> <?= $material['is_premium'] ? '<span class="badge bg-warning text-dark">Premium</span>' : '' ?></td><td class="text-end"><button class="btn btn-sm btn-ghost" data-bs-toggle="modal" data-bs-target="#edit<?= (int)$material['id'] ?>">Edit</button><form class="d-inline" method="post" action="admin_actions.php" onsubmit="return confirm('Delete this material?')"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="delete_material"><input type="hidden" name="id" value="<?= (int)$material['id'] ?>"><button class="btn btn-sm btn-outline-danger rounded-4">Delete</button></form></td></tr><?php endforeach; ?></tbody></table></div></section>
        </div>
    </main>
</div>
<?php foreach ($materials as $material): ?><div class="modal fade" id="edit<?= (int)$material['id'] ?>" tabindex="-1"><div class="modal-dialog modal-lg modal-dialog-centered"><form class="modal-content glass text-white" method="post" action="admin_actions.php"><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><input type="hidden" name="action" value="update_material"><input type="hidden" name="id" value="<?= (int)$material['id'] ?>"><div class="modal-header border-secondary"><h5>Edit material</h5><button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body row g-3"><div class="col-12"><input name="title" class="form-control" value="<?= e($material['title']) ?>"></div><div class="col-md-6"><select name="subject_id" class="form-select"><?php foreach ($subjects as $subject): ?><option value="<?= (int)$subject['id'] ?>" <?= $subject['id']==$material['subject_id']?'selected':'' ?>><?= e($subject['name']) ?></option><?php endforeach; ?></select></div><div class="col-md-6"><select name="class_id" class="form-select"><?php foreach ($classes as $class): ?><option value="<?= (int)$class['id'] ?>" <?= $class['id']==$material['class_id']?'selected':'' ?>><?= e($class['name']) ?></option><?php endforeach; ?></select></div><div class="col-12"><textarea name="description" class="form-control" rows="3"><?= e($material['description']) ?></textarea></div><div class="col-12"><input name="tags" class="form-control" value="<?= e($material['tags']) ?>"></div><div class="col-12 d-flex gap-4"><label><input type="checkbox" name="is_published" <?= $material['is_published']?'checked':'' ?>> Published</label><label><input type="checkbox" name="is_featured" <?= $material['is_featured']?'checked':'' ?>> Featured</label><label><input type="checkbox" name="is_premium" <?= $material['is_premium']?'checked':'' ?>> Premium</label></div></div><div class="modal-footer border-secondary"><button class="btn btn-premium">Save changes</button></div></form></div></div><?php endforeach; ?>
<?php render_mobile_nav(); render_scripts(); ?>
