<?php
require __DIR__ . '/lib.php';
$user = requireLogin();
$flash = getFlash();
$stmt = db()->prepare('SELECT * FROM tickets WHERE user_id = :user_id ORDER BY updated_at DESC');
$stmt->execute(['user_id' => $user['id']]);
$tickets = $stmt->fetchAll();
?>
<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Dashboard</title><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Noto+Sans+Malayalam:wght@400;500;600;700&display=swap" rel="stylesheet"><link rel="stylesheet" href="/assets/style.css"></head><body><div class="dashboard-shell"><aside class="sidebar card"><div class="brand small"><div class="brand-mark">PS</div><div><strong><?= e($user['name']) ?></strong><p><?= e($user['email']) ?></p></div></div><a class="primary-btn full" href="/new-ticket.php">+ New Ticket</a><nav class="stack-links"><a href="/dashboard.php">My Tickets</a><a href="/">Home</a><a href="/logout.php">Logout</a></nav></aside><main class="main-panel"><?php if ($flash): ?><div class="flash <?= e($flash['type']) ?>"><?= e($flash['message']) ?></div><?php endif; ?><section class="panel-head"><div><span class="eyebrow">Customer workspace</span><h1>Your support conversations</h1></div></section><section class="ticket-list"><?php foreach ($tickets as $ticket): ?><a class="ticket-row card" href="/ticket.php?id=<?= (int) $ticket['id'] ?>"><div><strong><?= e($ticket['subject']) ?></strong><p><?= e($ticket['ticket_code']) ?> · <?= e($ticket['category']) ?> · Order <?= e((string) $ticket['order_reference']) ?></p></div><div class="align-right"><span class="badge <?= strtolower($ticket['status']) ?>"><?= e($ticket['status']) ?></span><small><?= e($ticket['updated_at']) ?></small></div></a><?php endforeach; ?><?php if (!$tickets): ?><div class="card empty">No tickets yet. Create your first premium support request.</div><?php endif; ?></section></main></div></body></html>
