<?php
require_once __DIR__ . '/functions.php';
require_once __DIR__ . '/partials.php';
$error = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $email = trim($_POST['email'] ?? '');
    $password = $_POST['password'] ?? '';
    $stmt = $pdo->prepare("SELECT * FROM users WHERE email = ? AND role = 'admin' LIMIT 1");
    $stmt->execute([$email]);
    $user = $stmt->fetch();
    if ($user && password_verify($password, $user['password_hash'])) {
        session_regenerate_id(true);
        $_SESSION['admin_id'] = (int)$user['id'];
        $_SESSION['admin_name'] = $user['name'];
        header('Location: admin.php');
        exit;
    }
    $error = 'Invalid admin credentials.';
}
render_head('Admin Login');
?>
<main class="container py-5 min-vh-100 d-grid align-items-center">
    <div class="row justify-content-center"><div class="col-md-7 col-lg-5">
        <form method="post" class="glass rounded-5 p-4 p-lg-5 reveal visible">
            <input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>">
            <div class="brand mb-4"><span class="brand-mark"><i class="bi bi-shield-lock fs-4"></i></span><span><strong class="fs-4">Admin Studio</strong><small class="d-block text-muted-premium">Secure upload console</small></span></div>
            <?php if ($error): ?><div class="alert alert-danger rounded-4"><?= e($error) ?></div><?php endif; ?>
            <label class="form-label">Email</label><input class="form-control mb-3" type="email" name="email" required>
            <label class="form-label">Password</label><input class="form-control mb-4" type="password" name="password" required>
            <button class="btn btn-premium btn-lg w-100">Sign in</button>
            <p class="small text-muted-premium mt-3 mb-0">Create an admin in the users table with a password_hash generated by PHP password_hash().</p>
        </form>
    </div></div>
</main>
<?php render_scripts(); ?>
