<?php
require_once 'config.php';
requireLogin();
function pendingFeeFilters(): array { return ['student'=>trim($_GET['student']??''),'class'=>trim($_GET['class']??''),'month'=>trim($_GET['month']??''),'payment_method'=>trim($_GET['payment_method']??''),'date_from'=>trim($_GET['date_from']??''),'date_to'=>trim($_GET['date_to']??'')]; }
function buildPendingFeesQuery(array $filters): array { $sql="SELECT f.id,f.student_id,f.class,f.amount,f.payment_method,f.date,f.month,f.status,f.months_count,f.verified_months,u.name AS student_name,u.class AS student_class FROM fees f JOIN users u ON f.student_id=u.id WHERE u.role='student' AND LOWER(COALESCE(f.status,'')) <> 'verified'"; $params=[]; if($filters['student']!==''){$sql.=" AND u.name LIKE ?";$params[]='%'.$filters['student'].'%';} if($filters['class']!==''){$sql.=" AND u.class = ?";$params[]=$filters['class'];} if($filters['month']!==''){$sql.=" AND DATE_FORMAT(f.month,'%Y-%m') = ?";$params[]=$filters['month'];} if($filters['payment_method']!==''){$sql.=" AND f.payment_method = ?";$params[]=$filters['payment_method'];} if($filters['date_from']!==''){$sql.=" AND DATE(f.date) >= ?";$params[]=$filters['date_from'];} if($filters['date_to']!==''){$sql.=" AND DATE(f.date) <= ?";$params[]=$filters['date_to'];} return [$sql." ORDER BY f.date DESC,f.id DESC",$params]; }
function xls($v){ return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function feeMonths($month,$count){$dt=new DateTime(($month?date('Y-m',strtotime($month)):date('Y-m')).'-01');$out=[];for($i=0;$i<max(1,(int)$count);$i++){$out[]=$dt->format('M Y');$dt->modify('+1 month');}return implode(', ',$out);} 
$filters=pendingFeeFilters(); [$sql,$params]=buildPendingFeesQuery($filters); $stmt=$pdo->prepare($sql); $stmt->execute($params); $fees=$stmt->fetchAll(PDO::FETCH_ASSOC);
$filename='pending_fees_'.date('Ymd_His').'.xls'; header('Content-Type: application/vnd.ms-excel; charset=utf-8'); header('Content-Disposition: attachment; filename='.$filename); header('Pragma: no-cache'); header('Expires: 0');
?>
<html><head><meta charset="utf-8"><style>table{border-collapse:collapse}th,td{border:1px solid #9ca3af;padding:8px;mso-number-format:"\@"}.title{font-size:18px;font-weight:bold;background:#2563eb;color:white}.head{font-weight:bold;background:#dbeafe}.money{mso-number-format:"₹#,##0.00"}</style></head><body><table><tr><td colspan="10" class="title">School Name - Pending Fee Export</td></tr><tr><td colspan="10">Generated: <?= xls(date('d M Y h:i A')) ?> | Filters: Student <?= xls($filters['student'] ?: 'All') ?>, Class <?= xls($filters['class'] ?: 'All') ?>, Month <?= xls($filters['month'] ?: 'All') ?>, Method <?= xls($filters['payment_method'] ?: 'All') ?></td></tr><tr class="head"><th>No</th><th>Student Name</th><th>Class</th><th>Fee Amount</th><th>Months Count</th><th>Total Amount</th><th>Month</th><th>Payment Method</th><th>Date</th><th>Status</th></tr><?php $no=1; foreach($fees as $f): $count=(int)($f['months_count']?:1); $total=(float)$f['amount']*$count; ?><tr><td><?= $no++ ?></td><td><?= xls($f['student_name']) ?></td><td><?= xls($f['student_class'] ?: $f['class']) ?></td><td class="money"><?= number_format((float)$f['amount'],2,'.','') ?></td><td><?= $count ?></td><td class="money"><?= number_format($total,2,'.','') ?></td><td><?= xls(feeMonths($f['month'],$count)) ?></td><td><?= xls($f['payment_method']) ?></td><td><?= xls($f['date']) ?></td><td><?= xls($f['status']) ?></td></tr><?php endforeach; ?></table></body></html>
