CREATE DATABASE IF NOT EXISTS digital_id CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE digital_id;

CREATE TABLE roles (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE, description VARCHAR(255), is_system TINYINT(1) NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE permissions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(120) NOT NULL UNIQUE, description VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE role_permissions (role_id INT UNSIGNED NOT NULL, permission_id INT UNSIGNED NOT NULL, PRIMARY KEY(role_id, permission_id), FOREIGN KEY(role_id) REFERENCES roles(id) ON DELETE CASCADE, FOREIGN KEY(permission_id) REFERENCES permissions(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE madrasas (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(160) NOT NULL, district VARCHAR(120) NOT NULL, status ENUM('enabled','disabled') NOT NULL DEFAULT 'enabled', sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, INDEX(status), INDEX(district)) ENGINE=InnoDB;
CREATE TABLE positions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, username VARCHAR(60) NOT NULL UNIQUE, password_hash VARCHAR(255) NOT NULL, email VARCHAR(190) NOT NULL UNIQUE, email_verified TINYINT(1) NOT NULL DEFAULT 0, email_verify_token VARCHAR(128), role_id INT UNSIGNED NOT NULL, madrasa_id INT UNSIGNED NULL, position_id INT UNSIGNED NULL, status ENUM('pending','active','disabled','locked','deleted') NOT NULL DEFAULT 'pending', login_attempts INT NOT NULL DEFAULT 0, locked_until DATETIME NULL, last_login DATETIME NULL, remember_token_hash VARCHAR(255) NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(role_id) REFERENCES roles(id), FOREIGN KEY(madrasa_id) REFERENCES madrasas(id) ON DELETE SET NULL, FOREIGN KEY(position_id) REFERENCES positions(id) ON DELETE SET NULL, INDEX(status), INDEX(email_verified)) ENGINE=InnoDB;
CREATE TABLE user_profiles (user_id BIGINT UNSIGNED PRIMARY KEY, full_name VARCHAR(160) NOT NULL, address VARCHAR(255), place VARCHAR(120), district VARCHAR(120), state VARCHAR(120), country VARCHAR(120), living_place VARCHAR(160), working_place VARCHAR(160), certificate_number VARCHAR(80), msr_number VARCHAR(80), phone VARCHAR(40), photo VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE otps (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, email VARCHAR(190) NOT NULL, purpose ENUM('email_verify','password_reset') NOT NULL, otp_hash VARCHAR(255) NOT NULL, resend_count INT NOT NULL DEFAULT 0, attempts INT NOT NULL DEFAULT 0, expires_at DATETIME NOT NULL, verified_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE, INDEX(email,purpose), INDEX(expires_at)) ENGINE=InnoDB;
CREATE TABLE password_reset_limits (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, email VARCHAR(190) NOT NULL, requested_at DATETIME NOT NULL, INDEX(email, requested_at)) ENGINE=InnoDB;
CREATE TABLE login_history (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, username VARCHAR(60), ip_address VARCHAR(45), user_agent VARCHAR(255), browser VARCHAR(120), location VARCHAR(160), success TINYINT(1) NOT NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(user_id), INDEX(created_at)) ENGINE=InnoDB;
CREATE TABLE activity_logs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NULL, action VARCHAR(80) NOT NULL, entity VARCHAR(80), entity_id BIGINT UNSIGNED NULL, ip_address VARCHAR(45), user_agent VARCHAR(255), metadata JSON NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE SET NULL, INDEX(action), INDEX(created_at)) ENGINE=InnoDB;
CREATE TABLE notifications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, user_id BIGINT UNSIGNED NOT NULL, title VARCHAR(160) NOT NULL, body TEXT, read_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;
CREATE TABLE email_preferences (user_id BIGINT UNSIGNED PRIMARY KEY, security_emails TINYINT(1) DEFAULT 1, product_emails TINYINT(1) DEFAULT 0, language VARCHAR(10) DEFAULT 'en', FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE) ENGINE=InnoDB;

INSERT INTO roles(name,is_system) VALUES ('Administrator',1),('Super Admin',1),('Madrasa Admin',1),('Staff',1),('Teacher',1),('Student',1),('Guest',1);
INSERT INTO positions(name) VALUES ('Administrator'),('Staff'),('Student'),('Teacher'),('Principal'),('Accountant'),('Volunteer'),('Office Staff');
INSERT INTO permissions(name) VALUES ('users.manage'),('roles.manage'),('madrasas.manage'),('positions.manage'),('certificates.manage'),('activity.view'),('profile.own');
INSERT INTO role_permissions(role_id, permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.name IN ('Administrator','Super Admin');
