<?php
declare(strict_types=1);
require_once __DIR__ . '/../config.php';
requireLogin();
if (!isset($_SESSION['role']) || strtoupper((string)$_SESSION['role']) !== 'ADMIN') { http_response_code(403); exit('Access Denied'); }
if (!function_exists('e')) { function e($v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); } }
function db(): mysqli { global $conn, $mysqli, $pdo; if (isset($conn) && $conn instanceof mysqli) return $conn; if (isset($mysqli) && $mysqli instanceof mysqli) return $mysqli; http_response_code(500); exit('Database connection not found in config.php'); }
function csrf_token(): string { if (empty($_SESSION['csrf_token'])) $_SESSION['csrf_token'] = bin2hex(random_bytes(32)); return $_SESSION['csrf_token']; }
function verify_csrf(): void { if ($_SERVER['REQUEST_METHOD']==='POST' && !hash_equals($_SESSION['csrf_token'] ?? '', $_POST['csrf_token'] ?? '')) { http_response_code(419); exit('Invalid CSRF token'); } }
function flash(string $type, string $message): void { $_SESSION['flash'][]=['type'=>$type,'message'=>$message]; }
function flashes(): array { $f=$_SESSION['flash']??[]; unset($_SESSION['flash']); return $f; }
function redirect_to(string $url): never { header('Location: '.$url); exit; }
function fetch_one(string $sql, string $types='', array $params=[]): ?array { $stmt=db()->prepare($sql); if(!$stmt) return null; if($types) $stmt->bind_param($types, ...$params); $stmt->execute(); $row=$stmt->get_result()->fetch_assoc(); $stmt->close(); return $row ?: null; }
function fetch_all(string $sql, string $types='', array $params=[]): array { $stmt=db()->prepare($sql); if(!$stmt) return []; if($types) $stmt->bind_param($types, ...$params); $stmt->execute(); $rows=$stmt->get_result()->fetch_all(MYSQLI_ASSOC); $stmt->close(); return $rows; }
function execute_stmt(string $sql, string $types='', array $params=[]): bool { $stmt=db()->prepare($sql); if(!$stmt) return false; if($types) $stmt->bind_param($types, ...$params); $ok=$stmt->execute(); $stmt->close(); return $ok; }
function current_admin_id(): int { return (int)($_SESSION['id'] ?? $_SESSION['user_id'] ?? 0); }
function is_locked(?string $lockUntil): bool { return !empty($lockUntil) && strtotime($lockUntil) > time(); }
function layout_start(string $title): void { $flashes=flashes(); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($title) ?></title><link rel="preconnect" href="https://cdn.jsdelivr.net"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link href="https://cdn.datatables.net/1.13.8/css/dataTables.bootstrap5.min.css" rel="stylesheet"><link href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.bootstrap5.min.css" rel="stylesheet"><link href="assets/css/admin.css" rel="stylesheet"></head><body class="admin-body"><script>window.csrfToken='<?= e(csrf_token()) ?>';</script><div class="admin-shell"><?php include __DIR__ . '/admin_sidebar.php'; ?><main class="admin-main"><?php include __DIR__ . '/admin_header.php'; ?><div class="admin-content"><div class="toast-container position-fixed top-0 end-0 p-3"></div><?php foreach($flashes as $f): ?><div class="alert alert-<?= e($f['type']) ?> alert-dismissible fade show rounded-4 shadow-sm" role="alert"><?= e($f['message']) ?><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div><?php endforeach; ?><?php }
function layout_end(): void { ?></div></main></div><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script><script src="https://code.jquery.com/jquery-3.7.1.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/jquery.dataTables.min.js"></script><script src="https://cdn.datatables.net/1.13.8/js/dataTables.bootstrap5.min.js"></script><script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js"></script><script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.bootstrap5.min.js"></script><script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"></script><script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.print.min.js"></script><script src="assets/js/admin.js"></script></body></html><?php }
function user_form(array $u=[], string $action='add_ustad.php'): void { $isEdit=!empty($u); ?>
<form method="post" class="needs-validation" novalidate><input type="hidden" name="csrf_token" value="<?= e(csrf_token()) ?>"><div class="row g-4"><div class="col-lg-8"><div class="premium-card p-4"><h5 class="fw-bold mb-4"><i class="bi bi-person-vcard me-2 text-primary"></i>User Details</h5><div class="row g-3"><div class="col-md-6 form-floating"><input required class="form-control" name="name" id="name" value="<?= e($u['name']??'') ?>" placeholder="Name"><label for="name">Full Name</label></div><div class="col-md-6 form-floating"><input required pattern="[A-Za-z0-9_.-]{3,50}" class="form-control" name="username" id="username" value="<?= e($u['username']??'') ?>" placeholder="Username"><label for="username">Username</label></div><div class="col-md-6 form-floating"><input type="email" required class="form-control" name="email" id="email" value="<?= e($u['email']??'') ?>" placeholder="Email"><label for="email">Email</label></div><div class="col-md-6 form-floating"><input class="form-control" name="class" id="class" value="<?= e($u['class']??'') ?>" placeholder="Class"><label for="class">Class</label></div><div class="col-md-6 form-floating"><select required class="form-select" name="role" id="role"><option value="ADMIN" <?= (($u['role']??'')==='ADMIN')?'selected':'' ?>>ADMIN</option><option value="TEACHER" <?= (($u['role']??'')==='TEACHER')?'selected':'' ?>>TEACHER</option></select><label for="role">Role</label></div><div class="col-md-6 form-floating"><input type="password" <?= $isEdit?'':'required' ?> minlength="8" class="form-control" name="password" id="password" placeholder="Password"><label for="password"><?= $isEdit?'New Password (optional)':'Password' ?></label></div></div></div></div><div class="col-lg-4"><div class="premium-card p-4"><h5 class="fw-bold mb-3">Account Controls</h5><div class="form-check form-switch mb-3"><input class="form-check-input" type="checkbox" name="email_locked" id="email_locked" value="1" <?= !empty($u['email_locked'])?'checked':'' ?>><label class="form-check-label" for="email_locked">Email locked</label></div><button class="btn btn-primary btn-rounded w-100 mb-2" type="submit"><i class="bi bi-check2-circle me-2"></i><?= $isEdit?'Update User':'Create User' ?></button><a class="btn btn-light btn-rounded w-100" href="manage_ustads.php">Cancel</a></div></div></div></form><?php }
